### ISSUE TITLE
"mined block failed verification"

### ISSUE THREAD

**Issue by sebseb7** [graft-project/GraftNetwork#116]
this is to be solved with the next fork?

```
21|graftd  | 2018-04-22 12:28:52.951    [RPC1]  ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1045    mined block failed verification
21|graftd  |
21|graftd  | 2018-04-22 13:06:07.968    [RPC1]  ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1045    mined block failed verification
21|graftd  |
21|graftd  | 2018-04-22 13:43:47.567    [RPC0]  ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1045    mined block failed verification
21|graftd  |
21|graftd  | 2018-04-22 13:56:07.537    [RPC0]  ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1045    mined block failed verification
21|graftd  |
21|graftd  | 2018-04-22 13:56:25.414    [RPC0]  ERROR   cn      src/cryptonote_core/cryptonote_core.cpp:1045    mined block failed verification

```

Miner hashrate is wasted now.

**Comment by sebseb7** [comment]
How will fork height be reached when no block is found ?

![image](https://user-images.githubusercontent.com/677956/39098056-5641f050-4665-11e8-80a5-c8d579efc8f5.png)

**Comment by plavirudar** [comment]
What do you get when you do `set_log 1` on your daemon? By default the daemon doesn't log the reason the block failed verification.

**Comment by jagerman** [comment]
This is not a minor bug but rather appears to be a serious exploit.  This wasn't affecting just cryptoknight or spacepools, this was **every single** graft pool.  It also didn't just end, it ended with the attacker scooping up around 175 blocks mined at low difficulty.

Here's the timing:

- Several +2h forged blocks were added to the chain
- At height 67272 (i.e. just after block 67271 was found) every pool become unable to find nodes.  Valid shares that should have become blocks were being rejected by `graftnoded`, as @sebseb7 reported.  (I really hope that he had the debug log with at least one rejected block because I think it could be immensely useful to know where this is coming from)
- This attack persisted for approximately 9 hours, during which an unknown attacker mined on a private chain, safe in the knowledge that, with rest of the network blocked, he could mine while excluding any competition for blocks.
- At the end of the 9 hours, and the first public pool block I see is 67448 on graftpool) the attacker reconnected his node to the network, suddenly releasing the ~175 node chain onto the network.
- Looking at the chain, it is clear that this entity had been mining the whole time on a concealed private chain; there *is* no 9 hour gap in the block chain record.


I have three major concerns with this:

The first is that we don't actually know what happened here.  I did isolate it to the node itself (as @sebseb7 confirms): the pool submits what should be a valid block but the node rejects it.  (More details below.)

My second concern is that, without isolating the root cause, we have no conclusive reason to suspect that the v9 fork is going to eliminate the issue.  It might—the attack did coincide with +2h forged timestamps—but the attack persisted long after any such blocks were no longer future blocks.  Right now this seems like a considerably more damaging an exploit than just a difficulty manipulation.

My last concern is that we have an unknown entity attacking the network and profiting from that attack.  Not just once—though this was the longest such attack, there have been at least two more and quite possibly other identical attacks in the days since the fork.  And of this all follows the chaos leading up to the v8 fork.  I hope the team is considering a blockchain rollback—at the very least putting the pieces in place should this attack happen again (and I think it will)—if for no other reason than to reassure the community that such threats are being taken very seriously.

---

As to what I was able to uncover:

I set up a pair of private node isolated from the network, stuck on 67272, with node code with debugging added to it that I was trying to use to try to figure out what the problem was.  With limited hash power at my disposal, I couldn't feasibly find actual shares that satisfied the the 800M difficulty to narrow down the exact cause (and so I'm hoping @sebseb7 got a chance to turn on verbose logging), but one thing I did try was editting the pool and node code to send and accept a lower difficulty share; the node accepted that one without issue.

I've uploaded the node's `lmdb` data here (https://imaginary.stream/graft-lmdb-67272.tar - about 6.6GB).  This is the data for a node stuck on exactly the blocked height that hasn't communicated with the network since (and as such it should still has all the mempool transactions as they were during the attack, in case something in them are significant).

To anyone not familiar with setting this up (as I wasn't): you need to make two copies of the data and run two `graftnoded` instances that don't communicate with the outside world.  I started the two with:
```
graftnoded --hide-my-port --add-exclusive-node 127.0.0.1:12345 --p2p-bind-ip 127.0.0.1 --p2p-bind-port 12325
```
and
```
graftnoded --hide-my-port --add-exclusive-node 127.0.0.1:12325 --p2p-bind-ip 127.0.0.1 --p2p-bind-port 12345 --rpc-bind-port 18781
```
which will keep them from syncing or sending to the main graft network.  (You need to start two because the node won't consider itself ready to go until it has synced with at least one other node).

**Comment by jagerman** [comment]
It looks like this is happening again right now: it's been just under an hour since the last block.  Given the current hashrate on known graft pools, the probability of that being bad luck is less than 1/100 of 1%.

But here's the new, extra bad detail: this time the attack had **no forged timestamp blocks** in the last 100+ blocks.  And *that* means v9 isn't going to fix this.

**Comment by sebseb7** [comment]
" I think it could be immensely useful to know where this is coming from"

from a random miner...

"and so I'm hoping @sebseb7 got a chance to turn on verbose logging"

the timestamp from the blocktemplate timestamp gets rejected. thats why nobody can make a block. To make a block at the pool I would need to modify timestamps too...

**Comment by plavirudar** [comment]
@sebseb7 from a cursory observation of the code, it looks like the rejection was not caused by timestamp issues. 

Unless I've misread the code, it seems to be the case that the rejection for timestamp occurs in lines 3096-3125 of `src/cryptonote_core/blockchain.cpp`, and throws an error if the block was rejected for timestamping reasons. However, since this error did not appear in your daemon logs, it could be potentially another bug that's being exploited by the attackers.

**Comment by sebseb7** [comment]
I have seen this error

  MERROR_VER("Timestamp of block with id: " << get_block_hash(b) << ", " << b.timestamp << ", less than median of last " << blockchain_timestamp_check_window << " blocks, " << median_ts);

**Comment by sebseb7** [comment]
" it could be potentially another bug that's being exploited by the attackers."

a potential attacker can control a lot if timestamps because hashrate can be rented easily. 

my advise would be to move to a hash algo that is not available for rent, to remove the ability of the attacker to forge a large percentage of timestamps.

It's fundamentally flawed to use the DAA to fight this type of attack. DAA can be exploited *always* as long as you can control the value of a lot of timestamps.

**Comment by iamamyth** [comment]
Switching PoW algorithms, while it may help in the short term, seems to obscure the real issue: The timestamp validation logic has serious internal inconsistencies. For one thing, timestamps have a forward bound based on the server time (plus an adjustment for clock skew), but a backwards bound based on the median of a certain number of past blocks. Therefore, as seen here, if the server accepts a slew of blocks right at the edge of the forward window, then new blocks could easily end up rejected for being too far in the past. This double-asymmetry (clock skew adjustment for forward checks, but not backward checks; server time for forward checks, but median block time for backward checks) has the particularly perverse side effect of rejecting a new block for being "too old" when it carries a strong guarantee of temporal ordering because it references the top block on the chain, whose hash would be difficult to predict. In other words, the current timestamp validation actively breaks proof of work: Simple server clock disagreement is all that's required to throw the network into disarray. One could, for example, compromise various time servers used by a majority of nodes, creating a chain split where the longest proof of work ends up rejected by the majority of nodes. One cannot, therefore, reduce the problem to a matter of hash power. Change the algorithm if you like, perhaps it will in fact alleviate the problem in the short term, but I suspect such a change carries the very real risk of papering over the deep implementation flaw, such that it rears its ugly head at an even more inopportune moment.

@zawy12 I suspect the aforementioned flaws also make building a suitable DAA harder: The timestamps are utter garbage and the server actively frustrates the symmetry you seem to want (leaps forward in time cancelled by later leaps backwards).

**Comment by jagerman** [comment]
That timestamp error is certainly going to be a problem, and is going to be **more** of a problem in v9 because the timestamp check window gets lowered from 60 to 11 -- which means a node that finds 6 +500s forged timestamps out of the last 11 then locks out all other (behaving) nodes from the chain.  That seem like it would be pretty easy to do with a short, high hashrate NiceHash order.  Right now you have to get at least 30, which still isn't all *that* difficult to accomplish.

But that timestamp error cannot be the only issue here, because for 7 of the 9 hours the most recent chain timestamp *wasn't* a future timestamp, i.e. that error wouldn't have been triggered.

**Comment by sebseb7** [comment]
". One could, for example, compromise various time servers used by a majority of nodes, "

One can simply click 10MH at nicehast, don't make it look a complicated thing.

**Comment by sebseb7** [comment]
"but I suspect such a change carries the very real risk of papering over the deep implementation flaw,"

for sure the timestamp validation is exploitable now. It will be always as long as you can control many of those timestamps...

**Comment by sebseb7** [comment]
the DAA is in an indefensible position as long as you can control the majority of those timestamps

**Comment by sebseb7** [comment]
"But that timestamp error cannot be the only issue here, because for 7 of the 9 hours the most recent chain timestamp wasn't a future timestamp, i.e. that error wouldn't have been triggered."

simply replay the data with an implementation of the function with more debug output...

**Comment by imperdin** [comment]
> @iamamyth Switching PoW algorithms, while it may help in the short term, seems to obscure the real issue.  
  
The issue is: Graft is under 51% attacks, and that should be first and foremost avoided.  
All of the major cons in the DAA could be solver at a later date but the most pressing matter is to immediately prevent this kind of abuse and also roll-back the network imminently as the attackers are the only one mining the blocks it will send a strong message that abuse will not be tolerated.  

Solving the vulnerabilities could be easily solved at a later date.

**Comment by jagerman** [comment]
One possible solution to the timestamp problem (which wouldn't require a fork, but just a node update for pools): if the timestamp would be invalid due to being under the median of the last 11 blocks, increase it (either to the median + 1, or to the time of the most recent block).

That avoids the issue of mining become useless for the rest of the pool for a few blocks if a timestamp forger happens to get 6/11 blocks.  Most importantly it would greatly remove the incentive to manipulate the timestamp in the first place.

**Comment by trestylez** [comment]
@sebseb7 "the DAA is in an indefensible position as long as you can control the majority of those timestamps"
Wasn't DERO under attack and seemed to have solved the problem? They are still using cryptonight for POW which is cheap on NH.

**Comment by jagerman** [comment]
Something that just occurred to me: the node only sends the block template to the pool once, and this is when it adds the time into the block template.  But that time is going to be rejected.  Is it possible that all someone had to do was restart a pool to get over the frozen chain?

**Comment by imperdin** [comment]
@trestylez DERO haven't released the source code, and most likely the attackers haven't bothered reverse-engineer a coin which isn't even listed on Tradeogre.  
  
Security by obscurity is not the correct approach, and we could properly evaluate their code **after** they release the source-code otherwise we can't evaluate their mitigations

**Comment by zawy12** [comment]
> if the server accepts a slew of blocks right at the edge of the forward window, then new blocks could easily end up rejected for being too far in the past. 

Although there may be more too it, I have to say "Bingo, give the man a prize." This is a 51% vulnerability that never occurred to me. I've known 51% could "own" the MTP, but I was never able to think of a significant problem that it would cause.  All coins have an MTP.  I don't see any fix this.  You have to allow a decent margin for forward times.  Even with the incredibly long MTP = 60 in cryptonote default (Bitcoin is 11), if a 51% miner keeps assigning 100 seconds ahead of real time (if that's the risky FTL you've chosen to try to fix this), it doesn't matter how far in the past the MTP is, or what the difficulty algorithm is.  Honest miners get blocked out.

Second prize goes to:

>  if the timestamp would be invalid due to being under the median of the last 11 blocks, increase it (either to the median + 1, or to the time of the most recent block).

I know Zcash does this.  I don't know about others.

**Comment by sebseb7** [comment]
"DERO haven't released the source code, "

thats not true

**Comment by sebseb7** [comment]
"This is a 51% vulnerability that never occurred to me."

As I told you, do some research first. Stop developing your stuff in production.

**Comment by imperdin** [comment]
[Link to Dero-atlantis](https://www.reddit.com/r/DeroProject/comments/8drahs/deroatlantis_cryptonote_with_truly_private_smart/) which is the new "immune" version

**Comment by zawy12** [comment]
Correction: the -7xT limit in LWMA does not prevent this because it does not limit the actual timestamps that are placed on the blockchain.  LWMA's symmetrical limits would have to be taken outside of the DA, to be a more general enforcement. I don't know if that or what @jagerman has suggested is best.

**Comment by sebseb7** [comment]
" to this aspect of whatever the full problem is."

you will be suprised how creative those people are...

**Comment by zawy12** [comment]
For those interested here is timestamp-based apparent solvetimes and the solvetimes based on when my node received the blocks

![image](https://user-images.githubusercontent.com/18004719/39133598-927d2166-46e2-11e8-9a5e-620307ca36ec.png)

**Comment by zawy12** [comment]
Using my equation above with MTP=11 and FTL = 500/120 = 4.2, this what size miner will continue to be a problem.

```FTL = ((MTP+1)*(1-HRF/2)+1)*(1-HRF)```

Solving gives HRF = 0.57 will be able to block good timestamps, 50% of the time.   So he might still block out good timestamps, but he can't drive difficulty nearly as low....so he has a lot less motivation to hang around.   Most attackers will leave after 20 blocks of the LWMA.   After a few days of attempting to attack, they will probably not show up very often.  This fork might be sufficient.

**Comment by zawy12** [comment]
Solevtime my node sees and blockchain's solve time are looking pretty good since 40 blocks before the fork. Some block are missing.

```
226 | 238
25 | 23
251 | 253
23 | 16
60 | 59
44 | 44
41 | 40
240 | 237
251 | 548
343 | 27
457 | 427
304 | 274
95 | 89
165 | 158
310 | 67
166 | 394
78 | 71
65 | 61
283 | 253
468 | 459
25 | 25
215 | 212
52 | 50
19 | 20
58 | 54
23 | 24
4 | 3
186 | 185
58 | 56
3 | 3
27 | 26
9 | 9
7 | 2
67 | 65
80 | 78
63 | 64
6 | 4
18 | 19
25 | 24
0 | 3
59 | 18
24 | 1
386 | 178
28 | 28
395 | 389
76 | 75
40 | 39
116 | 110
54 | 54
353 | 345
67 | 67
72 | 72
18 | 17
8 | 8
230 | 226
13 | 14
29 | 28
28 | 27
75 | 74
52 | 51
60 | 58
118 | 117
303 | 298
88 | 88
565 | 319
46 | 282
11 | 11
133 | 129
320 | 312
55 | 55
150 | 147
7 | 7
169 | 165
7 | 7
165 | 153
197 | 193
368 | 362
84 | 83
116 | 1
171 | 77
134 | 131
23 | 23
316 | 310
32 | 30
47 | 46
151 | 148
148 | 143
17 | 18
60 | 59
44 | 44
```
